//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: game.proto
namespace google.protobuf
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoginRequest")]
  public partial class LoginRequest : global::ProtoBuf.IExtensible
  {
    public LoginRequest() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CommResult")]
  public partial class CommResult : global::ProtoBuf.IExtensible
  {
    public CommResult() {}
    
    private int _Result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Result
    {
      get { return _Result; }
      set { _Result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Message")]
  public partial class Message : global::ProtoBuf.IExtensible
  {
    public Message() {}
    
    private int _entity_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"entity_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int entity_id
    {
      get { return _entity_id; }
      set { _entity_id = value; }
    }
    private float _press_time;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"press_time", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float press_time
    {
      get { return _press_time; }
      set { _press_time = value; }
    }
    private int _input_sequence_number;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"input_sequence_number", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int input_sequence_number
    {
      get { return _input_sequence_number; }
      set { _input_sequence_number = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Messages")]
  public partial class Messages : global::ProtoBuf.IExtensible
  {
    public Messages() {}
    
    private readonly global::System.Collections.Generic.List<google.protobuf.Message> _datas = new global::System.Collections.Generic.List<google.protobuf.Message>();
    [global::ProtoBuf.ProtoMember(1, Name=@"datas", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<google.protobuf.Message> datas
    {
      get { return _datas; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"WorlData")]
  public partial class WorlData : global::ProtoBuf.IExtensible
  {
    public WorlData() {}
    
    private readonly global::System.Collections.Generic.List<google.protobuf.EntityData> _datas = new global::System.Collections.Generic.List<google.protobuf.EntityData>();
    [global::ProtoBuf.ProtoMember(1, Name=@"datas", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<google.protobuf.EntityData> datas
    {
      get { return _datas; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EntityData")]
  public partial class EntityData : global::ProtoBuf.IExtensible
  {
    public EntityData() {}
    
    private int _entity_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"entity_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int entity_id
    {
      get { return _entity_id; }
      set { _entity_id = value; }
    }
    private float _position;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"position", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float position
    {
      get { return _position; }
      set { _position = value; }
    }
    private int _last_processed_input;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"last_processed_input", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int last_processed_input
    {
      get { return _last_processed_input; }
      set { _last_processed_input = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}